### ISSUE TITLE
Missing `master` branch

### ISSUE THREAD

**Issue by Neo23x0** [reversinglabs/reversinglabs-yara-rules#1]
Something happened to your `master` branch. 

People started noticing it since I use download links to packages generated from that branch. I don't know if I want to use rules from a development branch in production. 

https://github.com/Neo23x0/Loki/pull/148/files

**Comment by tpericin** [comment]
Hi Florian,

We've renamed the master branch for development. That was something we intended to do before the repo was made public but missed the window by a few hours.

Anyway, the main branch is just called development. These are all production ready rules and you can use them as such. We synchronize them with the private repo we use for rule development after they are tested.

Sorry for the confusion, and thanks for reporting the issue.

Best regards
