### ISSUE TITLE
Rule set uses YARA 4 syntax, which is incompatible with previous versions

### ISSUE THREAD

**Issue by Neo23x0** [reversinglabs/reversinglabs-yara-rules#3]
The rule set in `yara/certificate/blocklist.yara` uses a syntax, which cannot be used in previous versions of YARA. 

Previous Syntax
```yara
      for any i in (0 .. pe.number_of_signatures) : (
         pe.signatures[i].issuer contains "VeriSign Class 3 Code Signing 2010 CA" and
         pe.signatures[i].serial == "78:62:07:2d:dc:75:9e:5f:6a:61:4b:e9:b9:3b:d5:21"
      )
```

Syntax used in `blocklist.yara`
```yara
        for any s in pe.signatures: (
            s.subject contains "FAN-CHAI, TOV" and
            s.serial == "08:dd:cc:67:f8:ca:d6:92:96:07:e4:cd:a2:9b:35:03" and
            1564310268 <= s.not_after
        )
```

I don't know if you want your ruleset to be compatible with previous YARA versions or used the new syntax intentionally. 
I can only tell you that many products don't use YARA 4 yet.

**Comment by tpericin** [comment]
@Neo23x0 Thanks for reporting this. We're taking a look at it right now. Increasing the requirements to YARA 4 wasn't our intention.

**Comment by tpericin** [comment]
@Neo23x0 This should be fixed now. Could you double check that the rule is working as expected on your end as well? Thanks.
