### ISSUE TITLE
Unicode Characters in blocklist.yara

### ISSUE THREAD

**Issue by Neo23x0** [reversinglabs/reversinglabs-yara-rules#4]
The Unicode characters in the file `blocklist.yara` cause problems in different tools that process YARA rules. 
I cannot find any reference in the documentation but I am pretty sure that the standard doesn't allow Unicode characters in YARA rule files. 

Maybe you could include the statements in an encoded form? e.g. `重庆话语科技有限公司` as `\u91CD\u5E86\u8BDD\u8BED\u79D1\u6280\u6709\u9650\u516C\u53F8` 

Could you try to implement that and check if the rule would still match on the respective samples? 

![Screenshot 2020-10-05 at 14 25 54](https://user-images.githubusercontent.com/2851492/95079367-d2aa8e80-0716-11eb-89a2-61bebda08062.png)

**Comment by tpericin** [comment]
We've replaced unicode with hex escaped strings. This now seems to work fine. Additionally, there's a problem with the way old and new YARA matches certificate serial numbers. We've fixed that as well in the latest commit.

Thanks for reporting this issue.

**Comment by Neo23x0** [comment]
Awesome, thanks 👍
